export const prefix = 'cat?';
export const errorMsg = (err) => {return `Oopsie whoopsie! uwu we made a ficky wucky. The cattos are working VEWU HAWD to fix this!! \nError: ${err}`};
export const kittyImgHeaders = [
	"You had me at cat",
	"Kitty, my dear, I don't give a damn",
	"I'm going to give you a kitty you can't refuse",
	"Kitty, I've got a feeling we're not in Kansas anymore",
	"Here's looking at you, cat",
	"May the kitties be with you",
	"I love the smell of cats in the morning",
	"The stuff that kittens dreams are made of",
	"Kitty, I think this is the beginning of a beautiful friendship",
	"Cat. James Cat",
	"Show me the kitties!",
	"You're gonna need a bigger cat",
	"Mama always said life was like a box of kittens. You never know what you're gonna get",
	"We'll always have cats",
	"A boy's best friend is his cat",
	"Keep your friends close, but your cats closer",
	"Say \"hello\" to my little kitty!",
	"Gentlemen, you can't fight in here! This is the Cat Room!",
	"Listen to the cats. Children of the night. What music they make",
	"I feel the need - the need for cats!",
	"Nobody puts kitty in a corner",
	"I'll get you, my pretty, and your little cat, too!",
	"A million dollars isn't cool. You know what's cool? A billion cats",
	"The universe is big. It’s vast and complicated and ridiculous. And sometimes, very rarely, impossible things just happen and we call them cats",
	"Rule 1: The Cat lies",
	"Good kitties don’t need rules",
	"One may tolerate a world of demons for the sake of a cat",
	"I am definitely a madman with a cat!",
	"Do what I do. Hold tight and pretend it's a cat!",
	"Whole worlds pivot on acts of cats",
	"There’s always a cat to look at if you open your eyes!",
	"Cats can save planets or wreck them",
	"Some cats live more in 20 years than others do in 80. It's not the time that matters, it's the kitty",
	"In 900 years of time and space, I’ve never met a kitty who wasn't important",
	"Cats are cool"
]
